services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    volumes:
      - firebase_auth:/app/data/autharithmetic-firebase.json
    depends_on:
        - postgresql
      
  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data

volumes:
  firebase_auth:
    external: true